In [1]:
import math
import pandas as pd

In [2]:
math.cos(math.pi)

-1.0

In [3]:
data_oceania = pd.read_csv('data/gapminder_gdp_oceania.csv')

In [4]:
print(data_oceania)

       country  gdpPercap_1952  gdpPercap_1957  gdpPercap_1962  \
0    Australia     10039.59564     10949.64959     12217.22686
1  New Zealand     10556.57566     12247.39532     13175.67800

   gdpPercap_1967  gdpPercap_1972  gdpPercap_1977  gdpPercap_1982  \
0     14526.12465     16788.62948     18334.19751     19477.00928
1     14463.91893     16046.03728     16233.71770     17632.41040

   gdpPercap_1987  gdpPercap_1992  gdpPercap_1997  gdpPercap_2002  \
0     21888.88903     23424.76683     26997.93657     30687.75473
1     19007.19129     18363.32494     21050.41377     23189.80135

   gdpPercap_2007
0     34435.36744
1     25185.00911

In [5]:
data_oceania_country = pd.read_csv('data/gapminder_gdp_oceania.csv', index_col='country')
print(data_oceania_country)

             gdpPercap_1952  gdpPercap_1957  gdpPercap_1962  gdpPercap_1967  \
country
Australia       10039.59564     10949.64959     12217.22686     14526.12465
New Zealand     10556.57566     12247.39532     13175.67800     14463.91893

             gdpPercap_1972  gdpPercap_1977  gdpPercap_1982  gdpPercap_1987  \
country
Australia       16788.62948     18334.19751     19477.00928     21888.88903
New Zealand     16046.03728     16233.71770     17632.41040     19007.19129

             gdpPercap_1992  gdpPercap_1997  gdpPercap_2002  gdpPercap_2007
country
Australia       23424.76683     26997.93657     30687.75473     34435.36744
New Zealand     18363.32494     21050.41377     23189.80135     25185.00911

In [6]:
data_oceania_country.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2 entries, Australia to New Zealand
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   gdpPercap_1952  2 non-null      float64
 1   gdpPercap_1957  2 non-null      float64
 2   gdpPercap_1962  2 non-null      float64
 3   gdpPercap_1967  2 non-null      float64
 4   gdpPercap_1972  2 non-null      float64
 5   gdpPercap_1977  2 non-null      float64
 6   gdpPercap_1982  2 non-null      float64
 7   gdpPercap_1987  2 non-null      float64
 8   gdpPercap_1992  2 non-null      float64
 9   gdpPercap_1997  2 non-null      float64
 10  gdpPercap_2002  2 non-null      float64
 11  gdpPercap_2007  2 non-null      float64
dtypes: float64(12)
memory usage: 208.0+ bytes

In [7]:
data_oceania_country.columns

Index(['gdpPercap_1952', 'gdpPercap_1957', 'gdpPercap_1962', 'gdpPercap_1967',
       'gdpPercap_1972', 'gdpPercap_1977', 'gdpPercap_1982', 'gdpPercap_1987',
       'gdpPercap_1992', 'gdpPercap_1997', 'gdpPercap_2002', 'gdpPercap_2007'],
      dtype='object')

In [8]:
oceania_country_data = data_oceania_country

In [9]:
oceania_country_data.T

country           Australia  New Zealand
gdpPercap_1952  10039.59564  10556.57566
gdpPercap_1957  10949.64959  12247.39532
gdpPercap_1962  12217.22686  13175.67800
gdpPercap_1967  14526.12465  14463.91893
gdpPercap_1972  16788.62948  16046.03728
gdpPercap_1977  18334.19751  16233.71770
gdpPercap_1982  19477.00928  17632.41040
gdpPercap_1987  21888.88903  19007.19129
gdpPercap_1992  23424.76683  18363.32494
gdpPercap_1997  26997.93657  21050.41377
gdpPercap_2002  30687.75473  23189.80135
gdpPercap_2007  34435.36744  25185.00911

In [10]:
oceania_country_data.describe(include='all')

,gdpPercap_1952,gdpPercap_1957,gdpPercap_1962,gdpPercap_1967,gdpPercap_1972,gdpPercap_1977,gdpPercap_1982,gdpPercap_1987,gdpPercap_1992,gdpPercap_1997,gdpPercap_2002,gdpPercap_2007
count,2.000000,2.000000,2.000000,2.000000,2.00000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000
mean,10298.085650,11598.522455,12696.452430,14495.021790,16417.33338,17283.957605,18554.709840,20448.040160,20894.045885,24024.175170,26938.778040,29810.188275
std,365.560078,917.644806,677.727301,43.986086,525.09198,1485.263517,1304.328377,2037.668013,3578.979883,4205.533703,5301.853680,6540.991104
min,10039.595640,10949.649590,12217.226860,14463.918930,16046.03728,16233.717700,17632.410400,19007.191290,18363.324940,21050.413770,23189.801350,25185.009110
25%,10168.840645,11274.086022,12456.839645,14479.470360,16231.68533,16758.837652,18093.560120,19727.615725,19628.685412,22537.294470,25064.289695,27497.598692
50%,10298.085650,11598.522455,12696.452430,14495.021790,16417.33338,17283.957605,18554.709840,20448.040160,20894.045885,24024.175170,26938.778040,29810.188275
75%,10427.330655,11922.958888,12936.065215,14510.573220,16602.98143,17809.077558,19015.859560,21168.464595,22159.406358,25511.055870,28813.266385,32122.777858
max,10556.575660,12247.395320,13175.678000,14526.124650,16788.62948,18334.197510,19477.009280,21888.889030,23424.766830,26997.936570,30687.754730,34435.367440

In [11]:
americas_gdp_data = pd.read_csv('data/gapminder_gdp_americas.csv', index_col='country')

In [12]:
americas_gdp_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 25 entries, Argentina to Venezuela
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   continent       25 non-null     object
 1   gdpPercap_1952  25 non-null     float64
 2   gdpPercap_1957  25 non-null     float64
 3   gdpPercap_1962  25 non-null     float64
 4   gdpPercap_1967  25 non-null     float64
 5   gdpPercap_1972  25 non-null     float64
 6   gdpPercap_1977  25 non-null     float64
 7   gdpPercap_1982  25 non-null     float64
 8   gdpPercap_1987  25 non-null     float64
 9   gdpPercap_1992  25 non-null     float64
 10  gdpPercap_1997  25 non-null     float64
 11  gdpPercap_2002  25 non-null     float64
 12  gdpPercap_2007  25 non-null     float64
dtypes: float64(12), object(1)
memory usage: 2.7+ KB

In [13]:
americas_gdp_data.describe()

,gdpPercap_1952,gdpPercap_1957,gdpPercap_1962,gdpPercap_1967,gdpPercap_1972,gdpPercap_1977,gdpPercap_1982,gdpPercap_1987,gdpPercap_1992,gdpPercap_1997,gdpPercap_2002,gdpPercap_2007
count,25.000000,25.000000,25.000000,25.000000,25.000000,25.000000,25.000000,25.000000,25.000000,25.000000,25.000000,25.000000
mean,4079.062552,4616.043733,4901.541870,5668.253496,6491.334139,7352.007126,7506.737088,7793.400261,8044.934406,8889.300863,9287.677107,11003.031625
std,3001.727522,3312.381083,3421.740569,4160.885560,4754.404329,5355.602518,5530.490471,6665.039509,7047.089191,7874.225145,8895.817785,9713.209302
min,1397.717137,1544.402995,1662.137359,1452.057666,1654.456946,1874.298931,2011.159549,1823.015995,1456.309517,1341.726931,1270.364932,1201.637154
25%,2428.237769,2487.365989,2750.364446,3242.531147,4031.408271,4756.763836,4258.503604,4140.442097,4439.450840,4684.313807,4858.347495,5728.353514
50%,3048.302900,3780.546651,4086.114078,4643.393534,5305.445256,6281.290855,6434.501797,6360.943444,6618.743050,7113.692252,6994.774861,8948.102923
75%,3939.978789,4756.525781,5180.755910,5788.093330,6809.406690,7674.929108,8997.897412,7807.095818,8137.004775,9767.297530,8797.640716,11977.574960
max,13990.482080,14847.127120,16173.145860,19530.365570,21806.035940,24072.632130,25009.559140,29884.350410,32003.932240,35767.433030,39097.099550,42951.653090

In [14]:
print(americas_gdp_data)

                    continent  gdpPercap_1952  gdpPercap_1957  gdpPercap_1962  \
country
Argentina            Americas     5911.315053     6856.856212     7133.166023
Bolivia              Americas     2677.326347     2127.686326     2180.972546
Brazil               Americas     2108.944355     2487.365989     3336.585802
Canada               Americas    11367.161120    12489.950060    13462.485550
Chile                Americas     3939.978789     4315.622723     4519.094331
Colombia             Americas     2144.115096     2323.805581     2492.351109
Costa Rica           Americas     2627.009471     2990.010802     3460.937025
Cuba                 Americas     5586.538780     6092.174359     5180.755910
Dominican Republic   Americas     1397.717137     1544.402995     1662.137359
Ecuador              Americas     3522.110717     3780.546651     4086.114078
El Salvador          Americas     3048.302900     3421.523218     3776.803627
Guatemala            Americas     2428.237769     2617.155967     2750.364446
Haiti                Americas     1840.366939     1726.887882     1796.589032
Honduras             Americas     2194.926204     2220.487682     2291.156835
Jamaica              Americas     2898.530881     4756.525781     5246.107524
Mexico               Americas     3478.125529     4131.546641     4581.609385
Nicaragua            Americas     3112.363948     3457.415947     3634.364406
Panama               Americas     2480.380334     2961.800905     3536.540301
Paraguay             Americas     1952.308701     2046.154706     2148.027146
Peru                 Americas     3758.523437     4245.256698     4957.037982
Puerto Rico          Americas     3081.959785     3907.156189     5108.344630
Trinidad and Tobago  Americas     3023.271928     4100.393400     4997.523971
United States        Americas    13990.482080    14847.127120    16173.145860
Uruguay              Americas     5716.766744     6150.772969     5603.357717
Venezuela            Americas     7689.799761     9802.466526     8422.974165

                     gdpPercap_1967  gdpPercap_1972  gdpPercap_1977  \
country
Argentina               8052.953021     9443.038526    10079.026740
Bolivia                 2586.886053     2980.331339     3548.097832
Brazil                  3429.864357     4985.711467     6660.118654
Canada                 16076.588030    18970.570860    22090.883060
Chile                   5106.654313     5494.024437     4756.763836
Colombia                2678.729839     3264.660041     3815.807870
Costa Rica              4161.727834     5118.146939     5926.876967
Cuba                    5690.268015     5305.445256     6380.494966
Dominican Republic      1653.723003     2189.874499     2681.988900
Ecuador                 4579.074215     5280.994710     6679.623260
El Salvador             4358.595393     4520.246008     5138.922374
Guatemala               3242.531147     4031.408271     4879.992748
Haiti                   1452.057666     1654.456946     1874.298931
Honduras                2538.269358     2529.842345     3203.208066
Jamaica                 6124.703451     7433.889293     6650.195573
Mexico                  5754.733883     6809.406690     7674.929108
Nicaragua               4643.393534     4688.593267     5486.371089
Panama                  4421.009084     5364.249663     5351.912144
Paraguay                2299.376311     2523.337977     3248.373311
Peru                    5788.093330     5937.827283     6281.290855
Puerto Rico             6929.277714     9123.041742     9770.524921
Trinidad and Tobago     5621.368472     6619.551419     7899.554209
United States          19530.365570    21806.035940    24072.632130
Uruguay                 5444.619620     5703.408898     6504.339663
Venezuela               9541.474188    10505.259660    13143.950950

                     gdpPercap_1982  gdpPercap_1987  gdpPercap_1992  \
country
Argentina               8997.897412     9139.671389     9308.418710
Bolivia                 3156.510452     2753.691490     2961.699694
Brazil                  7030.835878     7807.095818     6950.283021
Canada                 22898.792140    26626.515030    26342.884260
Chile                   5095.665738     5547.063754     7596.125964
Colombia                4397.575659     4903.219100     5444.648617
Costa Rica              5262.734751     5629.915318     6160.416317
Cuba                    7316.918107     7532.924763     5592.843963
Dominican Republic      2861.092386     2899.842175     3044.214214
Ecuador                 7213.791267     6481.776993     7103.702595
El Salvador             4098.344175     4140.442097     4444.231700
Guatemala               4820.494790     4246.485974     4439.450840
Haiti                   2011.159549     1823.015995     1456.309517
Honduras                3121.760794     3023.096699     3081.694603
Jamaica                 6068.051350     6351.237495     7404.923685
Mexico                  9611.147541     8688.156003     9472.384295
Nicaragua               3470.338156     2955.984375     2170.151724
Panama                  7009.601598     7034.779161     6618.743050
Paraguay                4258.503604     3998.875695     4196.411078
Peru                    6434.501797     6360.943444     4446.380924
Puerto Rico            10330.989150    12281.341910    14641.587110
Trinidad and Tobago     9119.528607     7388.597823     7370.990932
United States          25009.559140    29884.350410    32003.932240
Uruguay                 6920.223051     7452.398969     8137.004775
Venezuela              11152.410110     9883.584648    10733.926310

                     gdpPercap_1997  gdpPercap_2002  gdpPercap_2007
country
Argentina              10967.281950     8797.640716    12779.379640
Bolivia                 3326.143191     3413.262690     3822.137084
Brazil                  7957.980824     8131.212843     9065.800825
Canada                 28954.925890    33328.965070    36319.235010
Chile                  10118.053180    10778.783850    13171.638850
Colombia                6117.361746     5755.259962     7006.580419
Costa Rica              6677.045314     7723.447195     9645.061420
Cuba                    5431.990415     6340.646683     8948.102923
Dominican Republic      3614.101285     4563.808154     6025.374752
Ecuador                 7429.455877     5773.044512     6873.262326
El Salvador             5154.825496     5351.568666     5728.353514
Guatemala               4684.313807     4858.347495     5186.050003
Haiti                   1341.726931     1270.364932     1201.637154
Honduras                3160.454906     3099.728660     3548.330846
Jamaica                 7121.924704     6994.774861     7320.880262
Mexico                  9767.297530    10742.440530    11977.574960
Nicaragua               2253.023004     2474.548819     2749.320965
Panama                  7113.692252     7356.031934     9809.185636
Paraguay                4247.400261     3783.674243     4172.838464
Peru                    5838.347657     5909.020073     7408.905561
Puerto Rico            16999.433300    18855.606180    19328.709010
Trinidad and Tobago     8792.573126    11460.600230    18008.509240
United States          35767.433030    39097.099550    42951.653090
Uruguay                 9230.240708     7727.002004    10611.462990
Venezuela              10165.495180     8605.047831    11415.805690

In [15]:
americas_gdp_data.iloc[4, 2]

4315.622723

In [16]:
europe_gdp_data = pd.read_csv('data/gapminder_gdp_europe.csv', index_col='country')

In [17]:
europe_gdp_data.iloc[0, 0]

1601.056136

In [18]:
americas_gdp_data.T.loc["gdpPercap_1957":"gdpPercap_1977", "Cuba":"Peru"]

country,Cuba,Dominican Republic,Ecuador,El Salvador,Guatemala,Haiti,Honduras,Jamaica,Mexico,Nicaragua,Panama,Paraguay,Peru
gdpPercap_1957,6092.174359,1544.402995,3780.546651,3421.523218,2617.155967,1726.887882,2220.487682,4756.525781,4131.546641,3457.415947,2961.800905,2046.154706,4245.256698
gdpPercap_1962,5180.75591,1662.137359,4086.114078,3776.803627,2750.364446,1796.589032,2291.156835,5246.107524,4581.609385,3634.364406,3536.540301,2148.027146,4957.037982
gdpPercap_1967,5690.268015,1653.723003,4579.074215,4358.595393,3242.531147,1452.057666,2538.269358,6124.703451,5754.733883,4643.393534,4421.009084,2299.376311,5788.09333
gdpPercap_1972,5305.445256,2189.874499,5280.99471,4520.246008,4031.408271,1654.456946,2529.842345,7433.889293,6809.40669,4688.593267,5364.249663,2523.337977,5937.827283
gdpPercap_1977,6380.494966,2681.9889,6679.62326,5138.922374,4879.992748,1874.298931,3203.208066,6650.195573,7674.929108,5486.371089,5351.912144,3248.373311,6281.290855

In [19]:
print(americas_gdp_data)

                    continent  gdpPercap_1952  gdpPercap_1957  gdpPercap_1962  \
country
Argentina            Americas     5911.315053     6856.856212     7133.166023
Bolivia              Americas     2677.326347     2127.686326     2180.972546
Brazil               Americas     2108.944355     2487.365989     3336.585802
Canada               Americas    11367.161120    12489.950060    13462.485550
Chile                Americas     3939.978789     4315.622723     4519.094331
Colombia             Americas     2144.115096     2323.805581     2492.351109
Costa Rica           Americas     2627.009471     2990.010802     3460.937025
Cuba                 Americas     5586.538780     6092.174359     5180.755910
Dominican Republic   Americas     1397.717137     1544.402995     1662.137359
Ecuador              Americas     3522.110717     3780.546651     4086.114078
El Salvador          Americas     3048.302900     3421.523218     3776.803627
Guatemala            Americas     2428.237769     2617.155967     2750.364446
Haiti                Americas     1840.366939     1726.887882     1796.589032
Honduras             Americas     2194.926204     2220.487682     2291.156835
Jamaica              Americas     2898.530881     4756.525781     5246.107524
Mexico               Americas     3478.125529     4131.546641     4581.609385
Nicaragua            Americas     3112.363948     3457.415947     3634.364406
Panama               Americas     2480.380334     2961.800905     3536.540301
Paraguay             Americas     1952.308701     2046.154706     2148.027146
Peru                 Americas     3758.523437     4245.256698     4957.037982
Puerto Rico          Americas     3081.959785     3907.156189     5108.344630
Trinidad and Tobago  Americas     3023.271928     4100.393400     4997.523971
United States        Americas    13990.482080    14847.127120    16173.145860
Uruguay              Americas     5716.766744     6150.772969     5603.357717
Venezuela            Americas     7689.799761     9802.466526     8422.974165

                     gdpPercap_1967  gdpPercap_1972  gdpPercap_1977  \
country
Argentina               8052.953021     9443.038526    10079.026740
Bolivia                 2586.886053     2980.331339     3548.097832
Brazil                  3429.864357     4985.711467     6660.118654
Canada                 16076.588030    18970.570860    22090.883060
Chile                   5106.654313     5494.024437     4756.763836
Colombia                2678.729839     3264.660041     3815.807870
Costa Rica              4161.727834     5118.146939     5926.876967
Cuba                    5690.268015     5305.445256     6380.494966
Dominican Republic      1653.723003     2189.874499     2681.988900
Ecuador                 4579.074215     5280.994710     6679.623260
El Salvador             4358.595393     4520.246008     5138.922374
Guatemala               3242.531147     4031.408271     4879.992748
Haiti                   1452.057666     1654.456946     1874.298931
Honduras                2538.269358     2529.842345     3203.208066
Jamaica                 6124.703451     7433.889293     6650.195573
Mexico                  5754.733883     6809.406690     7674.929108
Nicaragua               4643.393534     4688.593267     5486.371089
Panama                  4421.009084     5364.249663     5351.912144
Paraguay                2299.376311     2523.337977     3248.373311
Peru                    5788.093330     5937.827283     6281.290855
Puerto Rico             6929.277714     9123.041742     9770.524921
Trinidad and Tobago     5621.368472     6619.551419     7899.554209
United States          19530.365570    21806.035940    24072.632130
Uruguay                 5444.619620     5703.408898     6504.339663
Venezuela               9541.474188    10505.259660    13143.950950

                     gdpPercap_1982  gdpPercap_1987  gdpPercap_1992  \
country
Argentina               8997.897412     9139.671389     9308.418710
Bolivia                 3156.510452     2753.691490     2961.699694
Brazil                  7030.835878     7807.095818     6950.283021
Canada                 22898.792140    26626.515030    26342.884260
Chile                   5095.665738     5547.063754     7596.125964
Colombia                4397.575659     4903.219100     5444.648617
Costa Rica              5262.734751     5629.915318     6160.416317
Cuba                    7316.918107     7532.924763     5592.843963
Dominican Republic      2861.092386     2899.842175     3044.214214
Ecuador                 7213.791267     6481.776993     7103.702595
El Salvador             4098.344175     4140.442097     4444.231700
Guatemala               4820.494790     4246.485974     4439.450840
Haiti                   2011.159549     1823.015995     1456.309517
Honduras                3121.760794     3023.096699     3081.694603
Jamaica                 6068.051350     6351.237495     7404.923685
Mexico                  9611.147541     8688.156003     9472.384295
Nicaragua               3470.338156     2955.984375     2170.151724
Panama                  7009.601598     7034.779161     6618.743050
Paraguay                4258.503604     3998.875695     4196.411078
Peru                    6434.501797     6360.943444     4446.380924
Puerto Rico            10330.989150    12281.341910    14641.587110
Trinidad and Tobago     9119.528607     7388.597823     7370.990932
United States          25009.559140    29884.350410    32003.932240
Uruguay                 6920.223051     7452.398969     8137.004775
Venezuela              11152.410110     9883.584648    10733.926310

                     gdpPercap_1997  gdpPercap_2002  gdpPercap_2007
country
Argentina              10967.281950     8797.640716    12779.379640
Bolivia                 3326.143191     3413.262690     3822.137084
Brazil                  7957.980824     8131.212843     9065.800825
Canada                 28954.925890    33328.965070    36319.235010
Chile                  10118.053180    10778.783850    13171.638850
Colombia                6117.361746     5755.259962     7006.580419
Costa Rica              6677.045314     7723.447195     9645.061420
Cuba                    5431.990415     6340.646683     8948.102923
Dominican Republic      3614.101285     4563.808154     6025.374752
Ecuador                 7429.455877     5773.044512     6873.262326
El Salvador             5154.825496     5351.568666     5728.353514
Guatemala               4684.313807     4858.347495     5186.050003
Haiti                   1341.726931     1270.364932     1201.637154
Honduras                3160.454906     3099.728660     3548.330846
Jamaica                 7121.924704     6994.774861     7320.880262
Mexico                  9767.297530    10742.440530    11977.574960
Nicaragua               2253.023004     2474.548819     2749.320965
Panama                  7113.692252     7356.031934     9809.185636
Paraguay                4247.400261     3783.674243     4172.838464
Peru                    5838.347657     5909.020073     7408.905561
Puerto Rico            16999.433300    18855.606180    19328.709010
Trinidad and Tobago     8792.573126    11460.600230    18008.509240
United States          35767.433030    39097.099550    42951.653090
Uruguay                 9230.240708     7727.002004    10611.462990
Venezuela              10165.495180     8605.047831    11415.805690

In [20]:
americas_gdp_data.iloc[2:10, 2:5].describe()

       gdpPercap_1957  gdpPercap_1962  gdpPercap_1967
count        8.000000        8.000000        8.000000
mean      4502.984895     4775.057645     5422.078701
std       3519.902532     3681.484391     4498.960413
min       1544.402995     1662.137359     1653.723003
25%       2446.475887     3125.527129     3242.080727
50%       3385.278726     3773.525551     4370.401024
75%       4759.760632     4684.509726     5252.557738
max      12489.950060    13462.485550    16076.588030

In [21]:
subset = americas_gdp_data.loc['Cuba':"Peru", 'gdpPercap_1962':'gdpPercap_2002']

In [22]:
print(subset)

                    gdpPercap_1962  gdpPercap_1967  gdpPercap_1972  \
country
Cuba                   5180.755910     5690.268015     5305.445256
Dominican Republic     1662.137359     1653.723003     2189.874499
Ecuador                4086.114078     4579.074215     5280.994710
El Salvador            3776.803627     4358.595393     4520.246008
Guatemala              2750.364446     3242.531147     4031.408271
Haiti                  1796.589032     1452.057666     1654.456946
Honduras               2291.156835     2538.269358     2529.842345
Jamaica                5246.107524     6124.703451     7433.889293
Mexico                 4581.609385     5754.733883     6809.406690
Nicaragua              3634.364406     4643.393534     4688.593267
Panama                 3536.540301     4421.009084     5364.249663
Paraguay               2148.027146     2299.376311     2523.337977
Peru                   4957.037982     5788.093330     5937.827283

                    gdpPercap_1977  gdpPercap_1982  gdpPercap_1987  \
country
Cuba                   6380.494966     7316.918107     7532.924763
Dominican Republic     2681.988900     2861.092386     2899.842175
Ecuador                6679.623260     7213.791267     6481.776993
El Salvador            5138.922374     4098.344175     4140.442097
Guatemala              4879.992748     4820.494790     4246.485974
Haiti                  1874.298931     2011.159549     1823.015995
Honduras               3203.208066     3121.760794     3023.096699
Jamaica                6650.195573     6068.051350     6351.237495
Mexico                 7674.929108     9611.147541     8688.156003
Nicaragua              5486.371089     3470.338156     2955.984375
Panama                 5351.912144     7009.601598     7034.779161
Paraguay               3248.373311     4258.503604     3998.875695
Peru                   6281.290855     6434.501797     6360.943444

                    gdpPercap_1992  gdpPercap_1997  gdpPercap_2002
country
Cuba                   5592.843963     5431.990415     6340.646683
Dominican Republic     3044.214214     3614.101285     4563.808154
Ecuador                7103.702595     7429.455877     5773.044512
El Salvador            4444.231700     5154.825496     5351.568666
Guatemala              4439.450840     4684.313807     4858.347495
Haiti                  1456.309517     1341.726931     1270.364932
Honduras               3081.694603     3160.454906     3099.728660
Jamaica                7404.923685     7121.924704     6994.774861
Mexico                 9472.384295     9767.297530    10742.440530
Nicaragua              2170.151724     2253.023004     2474.548819
Panama                 6618.743050     7113.692252     7356.031934
Paraguay               4196.411078     4247.400261     3783.674243
Peru                   4446.380924     5838.347657     5909.020073

In [23]:
subset.describe()

,gdpPercap_1962,gdpPercap_1967,gdpPercap_1972,gdpPercap_1977,gdpPercap_1982,gdpPercap_1987,gdpPercap_1992,gdpPercap_1997,gdpPercap_2002
count,13.000000,13.000000,13.000000,13.000000,13.000000,13.000000,13.000000,13.000000,13.000000
mean,3511.354464,4041.986799,4482.274785,5040.892410,5253.515778,5041.350836,4882.418630,5166.042625,5270.615351
std,1282.412026,1640.109390,1814.019832,1780.898643,2211.785487,2139.097998,2284.907494,2328.343339,2423.622475
min,1662.137359,1452.057666,1654.456946,1874.298931,2011.159549,1823.015995,1456.309517,1341.726931,1270.364932
25%,2291.156835,2538.269358,2529.842345,3248.373311,3470.338156,3023.096699,3081.694603,3614.101285,3783.674243
50%,3634.364406,4421.009084,4688.593267,5351.912144,4820.494790,4246.485974,4444.231700,5154.825496,5351.568666
75%,4581.609385,5690.268015,5364.249663,6380.494966,7009.601598,6481.776993,6618.743050,7113.692252,6340.646683
max,5246.107524,6124.703451,7433.889293,7674.929108,9611.147541,8688.156003,9472.384295,9767.297530,10742.440530

In [24]:
print("where are values large?\n", subset > 4200)

where are values large?
                     gdpPercap_1962  gdpPercap_1967  gdpPercap_1972  \
country
Cuba                          True            True            True
Dominican Republic           False           False           False
Ecuador                      False            True            True
El Salvador                  False            True            True
Guatemala                    False           False           False
Haiti                        False           False           False
Honduras                     False           False           False
Jamaica                       True            True            True
Mexico                        True            True            True
Nicaragua                    False            True            True
Panama                       False            True            True
Paraguay                     False           False           False
Peru                          True            True            True

                    gdpPercap_1977  gdpPercap_1982  gdpPercap_1987  \
country
Cuba                          True            True            True
Dominican Republic           False           False           False
Ecuador                       True            True            True
El Salvador                   True           False           False
Guatemala                     True            True            True
Haiti                        False           False           False
Honduras                     False           False           False
Jamaica                       True            True            True
Mexico                        True            True            True
Nicaragua                     True           False           False
Panama                        True            True            True
Paraguay                     False            True           False
Peru                          True            True            True

                    gdpPercap_1992  gdpPercap_1997  gdpPercap_2002
country
Cuba                          True            True            True
Dominican Republic           False           False            True
Ecuador                       True            True            True
El Salvador                   True            True            True
Guatemala                     True            True            True
Haiti                        False           False           False
Honduras                     False           False           False
Jamaica                       True            True            True
Mexico                        True            True            True
Nicaragua                    False           False           False
Panama                        True            True            True
Paraguay                     False            True           False
Peru                          True            True            True

In [25]:
greater_than_4200 = subset > 4200
print(subset[greater_than_4200])

                    gdpPercap_1962  gdpPercap_1967  gdpPercap_1972  \
country
Cuba                   5180.755910     5690.268015     5305.445256
Dominican Republic             NaN             NaN             NaN
Ecuador                        NaN     4579.074215     5280.994710
El Salvador                    NaN     4358.595393     4520.246008
Guatemala                      NaN             NaN             NaN
Haiti                          NaN             NaN             NaN
Honduras                       NaN             NaN             NaN
Jamaica                5246.107524     6124.703451     7433.889293
Mexico                 4581.609385     5754.733883     6809.406690
Nicaragua                      NaN     4643.393534     4688.593267
Panama                         NaN     4421.009084     5364.249663
Paraguay                       NaN             NaN             NaN
Peru                   4957.037982     5788.093330     5937.827283

                    gdpPercap_1977  gdpPercap_1982  gdpPercap_1987  \
country
Cuba                   6380.494966     7316.918107     7532.924763
Dominican Republic             NaN             NaN             NaN
Ecuador                6679.623260     7213.791267     6481.776993
El Salvador            5138.922374             NaN             NaN
Guatemala              4879.992748     4820.494790     4246.485974
Haiti                          NaN             NaN             NaN
Honduras                       NaN             NaN             NaN
Jamaica                6650.195573     6068.051350     6351.237495
Mexico                 7674.929108     9611.147541     8688.156003
Nicaragua              5486.371089             NaN             NaN
Panama                 5351.912144     7009.601598     7034.779161
Paraguay                       NaN     4258.503604             NaN
Peru                   6281.290855     6434.501797     6360.943444

                    gdpPercap_1992  gdpPercap_1997  gdpPercap_2002
country
Cuba                   5592.843963     5431.990415     6340.646683
Dominican Republic             NaN             NaN     4563.808154
Ecuador                7103.702595     7429.455877     5773.044512
El Salvador            4444.231700     5154.825496     5351.568666
Guatemala              4439.450840     4684.313807     4858.347495
Haiti                          NaN             NaN             NaN
Honduras                       NaN             NaN             NaN
Jamaica                7404.923685     7121.924704     6994.774861
Mexico                 9472.384295     9767.297530    10742.440530
Nicaragua                      NaN             NaN             NaN
Panama                 6618.743050     7113.692252     7356.031934
Paraguay                       NaN     4247.400261             NaN
Peru                   4446.380924     5838.347657     5909.020073

In [26]:
subset[greater_than_4200].describe()

,gdpPercap_1962,gdpPercap_1967,gdpPercap_1972,gdpPercap_1977,gdpPercap_1982,gdpPercap_1987,gdpPercap_1992,gdpPercap_1997,gdpPercap_2002
count,4.000000,8.000000,8.000000,9.000000,8.000000,7.000000,8.000000,9.000000,9.000000
mean,4991.377700,5169.983863,5667.581521,6058.192457,6591.626257,6670.900548,6190.332631,6309.916444,6432.186990
std,299.911475,732.116603,1010.236158,905.756364,1651.169997,1357.486929,1803.872442,1722.505034,1857.430296
min,4581.609385,4358.595393,4520.246008,4879.992748,4258.503604,4246.485974,4439.450840,4247.400261,4563.808154
25%,4863.180833,4539.557932,5132.894349,5351.912144,5756.162210,6356.090470,4445.843618,5154.825496,5351.568666
50%,5068.896946,5166.830775,5334.847459,6281.290855,6722.051698,6481.776993,6105.793507,5838.347657,5909.020073
75%,5197.093813,5763.073745,6155.722135,6650.195573,7239.572977,7283.851962,7179.007867,7121.924704,6994.774861
max,5246.107524,6124.703451,7433.889293,7674.929108,9611.147541,8688.156003,9472.384295,9767.297530,10742.440530

In [35]:
americas_gdp_data.mean()

TypeError: Could not convert ['AmericasAmericasAmericasAmericasAmericasAmericasAmericasAmericasAmericasAmericasAmericasAmericasAmericasAmericasAmericasAmericasAmericasAmericasAmericasAmericasAmericasAmericasAmericasAmericasAmericas'] to numeric

This didn't work because the americas gdp data has an extra column "continent" that is filled with "Americas" values.

In order to fix this we can use pandas [DataFrame.drop](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.drop.html) like this:

`americas_gdp_data.drop('continent', axis=1)`

In [38]:
incontinent_americas_gdp_data = americas_gdp_data.drop('continent', axis=1)
incontinent_americas_gdp_data.mean()

gdpPercap_1952     4079.062552
gdpPercap_1957     4616.043733
gdpPercap_1962     4901.541870
gdpPercap_1967     5668.253496
gdpPercap_1972     6491.334139
gdpPercap_1977     7352.007126
gdpPercap_1982     7506.737088
gdpPercap_1987     7793.400261
gdpPercap_1992     8044.934406
gdpPercap_1997     8889.300863
gdpPercap_2002     9287.677107
gdpPercap_2007    11003.031625
dtype: float64

In [28]:
europe_gdp_data.mean()

gdpPercap_1952     5661.057435
gdpPercap_1957     6963.012816
gdpPercap_1962     8365.486814
gdpPercap_1967    10143.823757
gdpPercap_1972    12479.575246
gdpPercap_1977    14283.979110
gdpPercap_1982    15617.896551
gdpPercap_1987    17214.310727
gdpPercap_1992    17061.568084
gdpPercap_1997    19076.781802
gdpPercap_2002    21711.732422
gdpPercap_2007    25054.481636
dtype: float64

In [29]:
mask_higher = europe_gdp_data > europe_gdp_data.mean()

In [30]:
print(mask_higher)

                        gdpPercap_1952  gdpPercap_1957  gdpPercap_1962  \
country
Albania                          False           False           False
Austria                           True            True            True
Belgium                           True            True            True
Bosnia and Herzegovina           False           False           False
Bulgaria                         False           False           False
Croatia                          False           False           False
Czech Republic                    True            True            True
Denmark                           True            True            True
Finland                           True            True            True
France                            True            True            True
Germany                           True            True            True
Greece                           False           False           False
Hungary                          False           False           False
Iceland                           True            True            True
Ireland                          False           False           False
Italy                            False           False           False
Montenegro                       False           False           False
Netherlands                       True            True            True
Norway                            True            True            True
Poland                           False           False           False
Portugal                         False           False           False
Romania                          False           False           False
Serbia                           False           False           False
Slovak Republic                  False           False           False
Slovenia                         False           False           False
Spain                            False           False           False
Sweden                            True            True            True
Switzerland                       True            True            True
Turkey                           False           False           False
United Kingdom                    True            True            True

                        gdpPercap_1967  gdpPercap_1972  gdpPercap_1977  \
country
Albania                          False           False           False
Austria                           True            True            True
Belgium                           True            True            True
Bosnia and Herzegovina           False           False           False
Bulgaria                         False           False           False
Croatia                          False           False           False
Czech Republic                    True            True            True
Denmark                           True            True            True
Finland                           True            True            True
France                            True            True            True
Germany                           True            True            True
Greece                           False            True           False
Hungary                          False           False           False
Iceland                           True            True            True
Ireland                          False           False           False
Italy                            False           False           False
Montenegro                       False           False           False
Netherlands                       True            True            True
Norway                            True            True            True
Poland                           False           False           False
Portugal                         False           False           False
Romania                          False           False           False
Serbia                           False           False           False
Slovak Republic                  False           False           False
Slovenia                         False           False            True
Spain                            False           False           False
Sweden                            True            True            True
Switzerland                       True            True            True
Turkey                           False           False           False
United Kingdom                    True            True            True

                        gdpPercap_1982  gdpPercap_1987  gdpPercap_1992  \
country
Albania                          False           False           False
Austria                           True            True            True
Belgium                           True            True            True
Bosnia and Herzegovina           False           False           False
Bulgaria                         False           False           False
Croatia                          False           False           False
Czech Republic                   False           False           False
Denmark                           True            True            True
Finland                           True            True            True
France                            True            True            True
Germany                           True            True            True
Greece                           False           False            True
Hungary                          False           False           False
Iceland                           True            True            True
Ireland                          False           False            True
Italy                             True            True            True
Montenegro                       False           False           False
Netherlands                       True            True            True
Norway                            True            True            True
Poland                           False           False           False
Portugal                         False           False           False
Romania                          False           False           False
Serbia                           False           False           False
Slovak Republic                  False           False           False
Slovenia                          True            True           False
Spain                            False           False            True
Sweden                            True            True            True
Switzerland                       True            True            True
Turkey                           False           False           False
United Kingdom                    True            True            True

                        gdpPercap_1997  gdpPercap_2002  gdpPercap_2007
country
Albania                          False           False           False
Austria                           True            True            True
Belgium                           True            True            True
Bosnia and Herzegovina           False           False           False
Bulgaria                         False           False           False
Croatia                          False           False           False
Czech Republic                   False           False           False
Denmark                           True            True            True
Finland                           True            True            True
France                            True            True            True
Germany                           True            True            True
Greece                           False            True            True
Hungary                          False           False           False
Iceland                           True            True            True
Ireland                           True            True            True
Italy                             True            True            True
Montenegro                       False           False           False
Netherlands                       True            True            True
Norway                            True            True            True
Poland                           False           False           False
Portugal                         False           False           False
Romania                          False           False           False
Serbia                           False           False           False
Slovak Republic                  False           False           False
Slovenia                         False           False            True
Spain                             True            True            True
Sweden                            True            True            True
Switzerland                       True            True            True
Turkey                           False           False           False
United Kingdom                    True            True            True

In [31]:
wealth_score = mask_higher.aggregate('sum', axis=1) / len(europe_gdp_data.columns)

In [32]:
print(wealth_score)

country
Albania                   0.000000
Austria                   1.000000
Belgium                   1.000000
Bosnia and Herzegovina    0.000000
Bulgaria                  0.000000
Croatia                   0.000000
Czech Republic            0.500000
Denmark                   1.000000
Finland                   1.000000
France                    1.000000
Germany                   1.000000
Greece                    0.333333
Hungary                   0.000000
Iceland                   1.000000
Ireland                   0.333333
Italy                     0.500000
Montenegro                0.000000
Netherlands               1.000000
Norway                    1.000000
Poland                    0.000000
Portugal                  0.000000
Romania                   0.000000
Serbia                    0.000000
Slovak Republic           0.000000
Slovenia                  0.333333
Spain                     0.333333
Sweden                    1.000000
Switzerland               1.000000
Turkey                    0.000000
United Kingdom            1.000000
dtype: float64

In [33]:
europe_gdp_data.groupby(wealth_score).sum()

,gdpPercap_1952,gdpPercap_1957,gdpPercap_1962,gdpPercap_1967,gdpPercap_1972,gdpPercap_1977,gdpPercap_1982,gdpPercap_1987,gdpPercap_1992,gdpPercap_1997,gdpPercap_2002,gdpPercap_2007
0.000000,36916.854200,46110.918793,56850.065437,71324.848786,88569.346898,104459.358438,113553.768507,119649.599409,92380.047256,103772.937598,118590.929863,149577.357928
0.333333,16790.046878,20942.456800,25744.935321,33567.667670,45277.839976,53860.456750,59679.634020,64436.912960,67918.093220,80876.051580,102086.795210,122803.729520
0.500000,11807.544405,14505.000150,18380.449470,21421.846200,25377.727380,29056.145370,31914.712050,35517.678220,36310.666080,40723.538700,45564.308390,51403.028210
1.000000,104317.277560,127332.008735,149989.154201,178000.350040,215162.343140,241143.412730,263388.781960,296825.131210,315238.235970,346930.926170,385109.939210,427850.333420